export const GET_BEERS_REQUESTED = 'GET_BEERS_REQUESTED';
export const GET_BEERS_INIT_DONE = 'GET_BEERS_INIT_DONE';
export const GET_BEERS_MORE_DONE = 'GET_BEERS_MORE_DONE';
export const GET_BEERS_FAILED = 'GET_BEERS_FAILED';

export const GET_BEER_REQUESTED = 'GET_BEER_REQUESTED';
export const GET_BEER_DONE = 'GET_BEER_DONE';
export const GET_BEER_FAILED = 'GET_BEER_FAILED';;
